### ISSUE TITLE
yum mirror servers not responding

### ISSUE THREAD

**Issue by av06** [CentOS/mirrorlists-code#14]
Tried updating yum on CentOS 7.5, also tried installing python-msqldb packages via yum, but it gives a timeout error even after trying many mirrors.
`http://mirrors.service.networklayer.com/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] curl#7 - "Failed connect to mirrors.service.networklayer.com:80; Connection timed out"`
cc @arrfab  @avijc

**Comment by avijc** [comment]
You've reported this issue in the wrong place. It is unlikely that your problem is related to how we create and distribute lists of CentOS mirrors. In particular, mirrors.service.networklayer.com is not registered as a public CentOS mirror and is thus outside the scope of these scripts. Please see your repo files in /etc/yum.repos.d and search for occurrences of networklayer.com. If this does not bring you clarity, please ask your service provider (which is likely networklayer.com). If this still does not help, you can ask on the forums https://www.centos.org/forums/ but be advised that we will likely ask you to check the repo files and/or contact your service provider in any case. Please direct any further comments/questions somewhere else than this GitHub issue, which should probably be closed. Thanks!

**Comment by sladyn98** [comment]
@avijc Thanks for the reply, which repo could we redirect this question to ?

**Comment by avijc** [comment]
The problem described above is a local problem, not a problem with CentOS repositories or mirrorlist.centos.org. Beyond that, see the suggestions in my previous answer.

**Comment by arrfab** [comment]
Closing, as not a problem with mirrorlist code itself.
